import {chromium} from '@playwright/test';
import bundled from '@sparticuz/chromium';
import fs from 'node:fs';
const browser=await chromium.launch({executablePath:await bundled.executablePath(),args:bundled.args,headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');await page.locator('.mod-card').first().waitFor();await page.screenshot({path:'/home/user/craftly-desktop.png',fullPage:true});
await page.locator('[data-favorite]').first().click();await page.locator('.sidebar [data-page="favorites"]').click();if(await page.locator('.mod-card').count()!==1)throw Error('Favorites failed');
await page.locator('.sidebar [data-page="discover"]').click();await page.locator('#search').fill('dragon');if(await page.locator('.mod-card').count()!==1)throw Error('Search failed');
await page.locator('[data-mod]').first().click();await page.locator('.detail-modal').waitFor();await page.locator('[data-action="close"]').click();
await page.locator('[data-action="account"]').first().click();await page.locator('.auth-form').waitFor();await page.screenshot({path:'/home/user/craftly-login.png'});await page.locator('[data-action="close"]').click();
await page.setViewportSize({width:390,height:844});await page.locator('.mobile-nav [data-page="discover"]').click();await page.screenshot({path:'/home/user/craftly-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.locator('[data-action="language"]').click();if(await page.locator('html').getAttribute('dir')!=='rtl')throw Error('RTL failed');await page.screenshot({path:'/home/user/craftly-arabic.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('RTL overflow');
await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log('Browser checks passed: desktop, mobile, RTL, favorites, search, mod details, sign-in; no JS errors.');
