import {shouldShowWelcome} from './cache.js';
import {welcomeView} from './startup.js';
import {HOME_SECTIONS,sourcesView,sourceLink,externalURL} from './hub.js';
import {mountCarousel} from './carousel.js';
import {cloudApi,cloud,catalogPage,hubAvailable} from './cloud.js';
import {SUPABASE_URL} from './cloud-config.js';
import {createViews} from './views.js';
import {createForms} from './forms.js';
import {createTransfers} from './transfers.js';
import './style.css';
import {createIcons,Type,FileText,FileBox,CloudUpload,Upload,List,Mail,House,Bell,ArrowLeft,Paintbrush,SlidersHorizontal,Pause,Play,Gauge,Clock3,CalendarDays,CircleHelp,Cloud,RefreshCw,ArrowRight,ArrowUpRight,ArrowDownWideNarrow,Box,Boxes,Blocks,ChevronRight,ChevronDown,Gamepad2,Compass,Heart,Download,Sparkles,LayoutDashboard,Settings2,UserRound,Cuboid,Grid2x2,Puzzle,Layers2,Earth,Shirt,Search,CloudOff,Flame,Star,PackageCheck,PackageOpen,Plus,Image,Eye,Trash2,X,ShieldCheck,LockKeyhole,HardDrive,Info,Check,Languages,ImagePlus,PackagePlus,Send,LogOut} from 'lucide';
const icons={Type,FileText,FileBox,CloudUpload,Upload,List,Mail,House,Bell,ArrowLeft,Paintbrush,SlidersHorizontal,Pause,Play,Gauge,Clock3,CalendarDays,CircleHelp,Cloud,RefreshCw,ArrowRight,ArrowUpRight,ArrowDownWideNarrow,Box,Boxes,Blocks,ChevronRight,ChevronDown,Gamepad2,Compass,Heart,Download,Sparkles,LayoutDashboard,Settings2,UserRound,Cuboid,Grid2x2,Puzzle,Layers2,Earth,Shirt,Search,CloudOff,Flame,Star,PackageCheck,PackageOpen,Plus,Image,Eye,Trash2,X,ShieldCheck,LockKeyhole,HardDrive,Info,Check,Languages,ImagePlus,PackagePlus,Send,LogOut};
const native=window.CraftlyNative;
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const state={page:'discover',returnPage:'discover',category:'All mods',version:'all',minRating:0,search:'',sort:'new',mods:[],user:null,favorites:readJSON('craftly-guest-favorites',[]),downloads:[],loading:true,error:'',admin:new URLSearchParams(location.search).has('admin')||native?.isAdmin(),ar:localStorage.getItem('craftly-lang')==='ar',detailTab:'about',detailId:null,transferId:null,studioCategory:'All mods',studioSort:'new',studioLayout:'list',studioLimit:30,uploading:false,heroItems:[],heroIndex:0,homeSections:{},homeScroll:{},browseItems:[],favoriteItems:null,browseHasMore:false,sourceFilter:'all',scrollPositions:{},sources:[],sourcesLoading:false,sourcesError:''};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(en,ar)=>state.ar?ar:en;
const icon=(name)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const image=m=>m.image||'images/overworld.webp';
const count=n=>n===null?'—':Intl.NumberFormat('en',{notation:'compact'}).format(n||0);
const mb=n=>(Number(n||0)/1048576).toFixed(1)+' MB';
const fileSize=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':mb(n);
function hydrate(){createIcons({icons,attrs:{'stroke-width':1.75}});document.querySelectorAll('img').forEach(img=>{img.referrerPolicy='no-referrer';img.onerror=()=>{if(!img.dataset.fallback){img.dataset.fallback='1';img.src='images/overworld.webp';img.alt=t('Image unavailable · Craftly artwork','الصورة غير متاحة · صورة Craftly');}};});}
async function api(url,opts={}){try{return await cloudApi(url,opts);}catch(e){if(/fetch|network/i.test(e.message))throw Error(t('Cannot reach Supabase. Check your connection and retry.','تعذر الاتصال بـSupabase. تأكد من الإنترنت وحاول من جديد.'));throw e;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
let progressTimer;
const transfers=createTransfers({native,ticket:id=>api('/mods/'+id+'/download',{method:'POST'}),onChange:()=>{clearTimeout(progressTimer);progressTimer=setTimeout(()=>{if(state.page==='downloads'&&$('#results')){$('#results').innerHTML=views.downloadResults();hydrate();}if(state.page==='transfer'&&$('#main')){$('#main').innerHTML=views.transferDetail();hydrate();}},80);}});
const views=createViews({state,t,icon,esc,image,count,mb,transfers});
const forms=createForms({state,t,icon,esc,image,count,mb,heading:views.heading,modal,catLabel:views.catLabel,categories:views.categories});
function pageContent(){if(state.page==='sources')return sourcesView({state,t,esc,icon});if(state.page==='studio')return forms.studio();if(state.page==='detail')return views.detail();if(state.page==='transfer')return views.transferDetail();return views[state.page]?.()||views.discover();}
function render(){disposeCarousel?.();homeObserver?.disconnect();document.querySelectorAll('[data-home-row]').forEach(el=>state.homeScroll[el.dataset.homeRow]=el.scrollLeft);document.documentElement.lang=state.ar?'ar':'en';document.documentElement.dir=state.ar?'rtl':'ltr';document.body.dataset.page=state.page;native?.setDarkAppearance?.(state.page==='welcome'||!!$('#startup-splash:not(.leaving)'));if(state.page==='welcome'){$('#app').innerHTML=welcomeView({t,icon,admin:state.admin});hydrate();return;}$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#" data-page="discover"><span>${icon('box')}</span>craftly<span class="brand-dot">.</span></a><div class="sidebar-label">${t('YOUR LITTLE WORLD','عالمك الصغير')}</div><nav>${views.nav()}</nav><div class="sidebar-bottom"><div class="sidebar-art"><img src="images/cottage.webp" alt="Minecraft cottage"><div><b>${t('A little more wonder.','قليل من السحر.')}</b><p>${t('Make Minecraft yours.','ماينكرافت، على ذوقك.')}</p></div></div><button class="menu-row" data-action="studio">${icon('layout-dashboard')}<b>${t('Creator studio','استوديو الأدمن')}</b>${icon('arrow-up-right')}</button><small>Craftly 1.4 · Bedrock Edition</small></div></aside><div class="main-shell">${views.topbar()}<main id="main">${pageContent()}</main><footer class="footer">${t('An independent Minecraft companion. Not affiliated with Mojang or Microsoft.','تطبيق مستقل وغير تابع لـMojang أو Microsoft.')}<span>© ${new Date().getFullYear()} Craftly</span></footer></div><nav class="mobile-nav" aria-label="${t('Main navigation','التنقل الرئيسي')}">${views.nav()}</nav>`;hydrate();mountHome();}
function modal(content,cls=''){if(state.uploading)return;clearTimeout(window.toastTimer);$('#toast').classList.remove('show');releaseCoverPreview();window.lastFocus=document.activeElement;$('#overlay').innerHTML=`<div class="modal-backdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="Craftly"><button class="modal-close icon-button" data-action="close" aria-label="${t('Close','إغلاق')}">${icon('x')}</button>${content}</section></div>`;document.body.classList.add('modal-open');hydrate();setTimeout(()=>$('.modal input:not([type=hidden]), .modal button')?.focus(),40);}
function close(){if(state.uploading){toast(t('Keep this screen open while your mod is publishing.','خلي هاد الشاشة مفتوحة حتى يسالي النشر.'));return false;}releaseCoverPreview();$('#overlay').innerHTML='';document.body.classList.remove('modal-open');window.lastFocus?.isConnected&&window.lastFocus.focus();}
function navigate(page){state.scrollPositions[state.page]=scrollY;if(close()===false)return;state.page=page;render();window.scrollTo({top:state.scrollPositions[page]||0,behavior:'instant'});if(page==='browse'||page==='favorites')refreshResults();if(page==='sources')loadSources();if(page==='studio')loadStudio();if(page==='downloads'&&state.user)api('/downloads').then(d=>{state.downloads=d;if(state.page==='downloads'){$('#results').innerHTML=views.downloadResults();hydrate();}}).catch(e=>toast(e.message));}

function detail(id){if(!state.mods.some(m=>m.id===id))return toast(t('This add-on is no longer available.','هذه الإضافة لم تعد متوفرة.'));if(state.page!=='detail'){state.scrollPositions[state.page]=scrollY;state.returnPage=state.page;}state.detailId=id;state.detailTab='about';state.page='detail';close();render();window.scrollTo({top:0});}
let loadEpoch=0,loadTask;
async function load({force=false}={}){if(loadTask&&!force)return loadTask;const epoch=++loadEpoch;if(force)state.homeSections={};state.loading=state.mods.length===0;state.error='';render();const work=(async()=>{try{const [u,mods]=await Promise.all([api('/me',{force}),api('/mods',{force})]);if(epoch!==loadEpoch)return;const previous=state.user?.id;state.user=u;transfers.setOwner(u?.id);mergeMods(mods);state.heroItems=[...mods].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,5);if(previous!==u?.id)state.downloads=[];state.favorites=u?u.favorites:readJSON('craftly-guest-favorites',[]);}catch(e){if(epoch===loadEpoch)state.error=e.message;}finally{if(epoch===loadEpoch){state.loading=false;const hero=await catalogPage({sort:'updated',version:state.version,limit:5}).catch(()=>null);if(epoch!==loadEpoch)return;if(hero){state.heroItems=hero.items;state.heroFetchedAt=Date.now();mergeMods(hero.items);}render();if(state.page==='browse'||state.page==='favorites')refreshResults();if(state.page==='studio')loadStudio();}}})();loadTask=work;try{await work;}finally{if(loadTask===work)loadTask=null;}}
function refreshStudio(){const target=$('#studio-collection');if(target){target.innerHTML=forms.studioCollection();hydrate();}}
let coverObjectURL;
function releaseCoverPreview(){if(coverObjectURL){URL.revokeObjectURL(coverObjectURL);coverObjectURL=null;}}
function uploadStage(event){const element=$('#upload-progress');if(!element)return;const stages=['validating','cover','package','publishing'];const index=stages.indexOf(event.stage);const labels={validating:t('Checking your files…','جاري التحقق من الملفات…'),cover:t('Uploading cover artwork…','جاري رفع صورة الغلاف…'),package:t('Uploading Minecraft package…','جاري رفع ملف المود…'),publishing:t('Publishing your add-on…','جاري نشر الإضافة…'),complete:t('Published successfully','تم النشر بنجاح'),cleanup:t('Cleaning up incomplete upload…','جاري تنظيف الرفع غير المكتمل…')};element.hidden=false;element.innerHTML=`<div class="upload-stage-label"><span class="upload-spinner"></span><b>${labels[event.stage]||''}</b></div><div class="upload-stage-steps">${stages.map((stage,i)=>`<span class="${i<index?'done':i===index?'active':''}"></span>`).join('')}</div><small>${event.file?esc(event.file)+' · '+fileSize(event.size):t('Secure upload · please keep the app open','رفع آمن · خلي التطبيق مفتوح')}</small>`;const packageStatus=$('#package-file-status');if(packageStatus&&event.stage==='package')packageStatus.textContent=t('Uploading securely to Supabase…','جاري الرفع بشكل آمن إلى Supabase…');const coverStatus=$('#cover-file-status');if(coverStatus&&event.stage==='package')coverStatus.textContent=t('Cover uploaded','تم رفع الصورة');}
function fileSelection(input){const file=input.files?.[0],isCover=input.name==='image',label=$(isCover?'#cover-file-label':'#package-file-label'),status=$(isCover?'#cover-file-status':'#package-file-status');if(!file){label.textContent=t('Tap to select a file','اضغط لاختيار ملف');status.textContent=t('No file selected','لم يتم اختيار ملف');if(isCover){releaseCoverPreview();$('#cover-preview').innerHTML=icon('image-plus');hydrate();}return;}const extension=file.name.split('.').at(-1).toLowerCase();const valid=(isCover?['png','jpg','jpeg','webp']:['mcaddon','mcpack','mcworld']).includes(extension)&&file.size>0&&file.size<=(isCover?8:50)*1048576;if(!valid){input.value='';status.textContent=t('Unsupported file type or size. Please choose another file.','نوع الملف أو حجمه غير مدعوم. اختار ملفاً آخر.');status.classList.add('invalid');label.textContent=t('Select another file','اختار ملفاً آخر');if(isCover){releaseCoverPreview();$('#cover-preview').innerHTML=icon('image-plus');hydrate();}return;}status.classList.remove('invalid');label.textContent=file.name;status.textContent=extension.toUpperCase()+' · '+fileSize(file.size)+' · '+t('Ready to upload','جاهز للرفع');if(isCover){releaseCoverPreview();coverObjectURL=URL.createObjectURL(file);const img=document.createElement('img');img.src=coverObjectURL;img.alt=t('Selected cover preview','معاينة الصورة المختارة');img.decoding='async';img.onerror=()=>{if(img.src!==coverObjectURL)return;releaseCoverPreview();input.value='';status.textContent=t('This image could not be decoded. Select a valid cover.','تعذر عرض الصورة. اختار صورة صالحة.');status.classList.add('invalid');label.textContent=t('Select another image','اختار صورة أخرى');$('#cover-preview').replaceChildren();};$('#cover-preview').replaceChildren(img);}}

async function favorite(id){try{state.favorites=state.user?await api('/favorites/'+id,{method:'POST'}):state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];if(!state.user)localStorage.setItem('craftly-guest-favorites',JSON.stringify(state.favorites));const y=scrollY;render();window.scrollTo({top:y});if(state.page==='favorites')refreshResults();toast(state.favorites.includes(id)?t('Saved to your favorites.','تمت الإضافة للمفضلة.'):t('Removed from favorites.','تمت الإزالة من المفضلة.'));}catch(e){toast(e.message);}}
async function download(id){const m=state.mods.find(m=>m.id===id);if(m&&sourceLink(m))return openSource(m);if(!state.user)return forms.login();if(!m)return toast(t('Refresh the catalog to download this add-on.','حدث الكتالوج لتحميل هذه الإضافة.'));close();state.returnPage='downloads';state.page='transfer';state.transferId=id;transfers.start(m);render();window.scrollTo({top:0});}
window.craftlyTransferEvent=event=>{transfers.receive(event);if(event.status==='complete'){toast(t('Download complete. Ready for Minecraft.','اكتمل التنزيل. واجد لماينكرافت.'));api('/downloads').then(d=>state.downloads=d).catch(()=>{});}};
window.craftlyDownloadDone=(ok,message)=>toast(message);
window.craftlyBack=()=>{if(state.page==='welcome'&&!$('.modal'))return false;if($('.modal')){close();return true;}if(['detail','transfer'].includes(state.page)){navigate(state.page==='transfer'?'downloads':state.returnPage);return true;}if(state.page!=='discover'){navigate('discover');return true;}return false;};
function settings(){modal(`<div class="sheet-handle"></div><div class="padded-modal"><p class="eyebrow">YOUR SPACE, YOUR WAY</p><h2>${t('Settings','الإعدادات')}</h2><div class="menu-card"><button class="menu-row" data-action="language">${icon('languages')}<b>${state.ar?'English':'العربية'}</b>${icon('chevron-right')}</button><button class="menu-row" data-action="versions">${icon('box')}<b>${t('Minecraft version','إصدار Minecraft')}</b>${icon('chevron-right')}</button><button class="menu-row" data-action="retry">${icon('refresh-cw')}<b>${t('Refresh catalog','تحديث الكتالوج')}</b>${icon('chevron-right')}</button></div><div class="info-note">${icon('shield-check')}<p>${t('Connected directly to your Supabase project. Your password is never embedded in the app.','ربط مباشر مع مشروع Supabase. كلمة المرور غير مدمجة في التطبيق.')}<br><span dir="ltr">${esc(new URL(SUPABASE_URL).host)}</span></p></div></div>`,'sheet');}
function storage(){let nativeSize=0;try{nativeSize=Number(native?.downloadStorageBytes?.()||0);}catch{}const total=native?nativeSize:[...transfers.jobs.values()].reduce((a,j)=>a+(j.blob?j.bytes:0),0);modal(`<div class="sheet-handle"></div><div class="padded-modal"><p class="eyebrow">ON THIS DEVICE</p><h2>${t('Manage storage','إدارة التخزين')}</h2><div class="storage-summary">${icon('hard-drive')}<strong>${mb(total)}</strong><span>${t('Craftly local files','ملفات Craftly المحلية')}</span></div><p>${t('Clear files retained inside Craftly. This does not delete your account, cloud mods, Minecraft worlds or copies already saved in your phone’s Downloads folder.','مسح الملفات داخل Craftly فقط. لا يحذف الحساب أو المودات السحابية أو عوالم اللعبة أو النسخ المحفوظة في مجلد تنزيلات الهاتف.')}</p><button class="primary full" data-action="clear-confirm">${icon('trash-2')}${t('Clear local files','مسح الملفات المحلية')}</button><p class="field-note">${t('In the browser, only this session’s in-memory files can be cleared.','في المتصفح، يمكن مسح الملفات المحفوظة في ذاكرة هذه الجلسة فقط.')}</p></div>`,'sheet');}
function notifications(){localStorage.setItem('craftly-seen',String(Date.now()));render();const latest=[...state.mods].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,10);modal(`<div class="sheet-handle"></div><div class="padded-modal"><h2>${t('Fresh from your creators','جديد صُنّاع المحتوى')}</h2><p class="muted">${t('Latest published add-ons. These are catalog updates, not push notifications.','آخر الإضافات المنشورة، وليست إشعارات فورية من النظام.')}</p>${latest.length?latest.map(m=>`<button class="notification-row" data-mod="${esc(m.id)}"><img src="${esc(image(m))}" alt=""><span><b>${esc(m.title)}</b><small>${new Date(m.createdAt).toLocaleDateString()}</small></span>${icon('chevron-right')}</button>`).join(''):views.empty('bell',t('All caught up','كلشي محدث'),t('New releases will appear here.','الإضافات الجديدة غادي تظهر هنا.'),false)}</div>`,'sheet');}
let disposeCarousel,homeObserver,searchTimer,resultEpoch=0;
function mergeMods(items){const map=new Map(state.mods.map(m=>[m.id,m]));for(const m of items)map.set(m.id,m);state.mods=[...map.values()];}
function mountHome(){if(state.page!=='discover')return;disposeCarousel?.();homeObserver?.disconnect();if(!state.loading&&Date.now()-(state.heroFetchedAt||0)>60000)refreshHero();disposeCarousel=mountCarousel($('.hero-carousel'),index=>state.heroIndex=index);document.querySelectorAll('[data-home-row]').forEach(el=>el.scrollLeft=state.homeScroll[el.dataset.homeRow]||0);homeObserver=new IntersectionObserver(entries=>entries.filter(e=>e.isIntersecting).forEach(e=>{homeObserver.unobserve(e.target);loadSection(e.target.dataset.homeSection);}),{rootMargin:'150px'});document.querySelectorAll('[data-home-section]').forEach(el=>homeObserver.observe(el));}
let heroPending=false;
async function refreshHero(){if(heroPending)return;heroPending=true;const version=state.version;try{const result=await catalogPage({sort:'updated',version,limit:5});if(version!==state.version)return;state.heroItems=result.items;state.heroFetchedAt=Date.now();mergeMods(result.items);if(state.page==='discover'){const target=$('.hero-carousel, .hero-skeleton, #main>.hero');if(target){disposeCarousel?.();target.outerHTML=views.hero();hydrate();disposeCarousel=mountCarousel($('.hero-carousel'),index=>state.heroIndex=index);}}}catch{}finally{heroPending=false;}}
const sectionPending=new Set();
async function loadSection(id,more=false){if(sectionPending.has(id)||state.homeSections[id]&&!more&&!state.homeSections[id].error&&Date.now()-state.homeSections[id].fetchedAt<60000)return;const def=HOME_SECTIONS.find(s=>s[0]===id);if(!def)return;const version=state.version;sectionPending.add(id);try{const old=state.homeSections[id]?.items||[];const result=await catalogPage({category:def[3],sort:def[4],version,limit:6,offset:more?old.length:0});if(version!==state.version)return;state.homeSections[id]={fetchedAt:Date.now(),items:more?[...old,...result.items]:result.items,hasMore:result.hasMore};mergeMods(result.items);}catch(e){state.homeSections[id]={items:[],error:e.message};}finally{sectionPending.delete(id);const target=$('#home-'+id);if(target&&version===state.version){const previous=target.querySelector('.home-row')?.scrollLeft||state.homeScroll[id]||0;target.innerHTML=views.homeSection(id);const row=target.querySelector('.home-row');if(row)row.scrollLeft=previous;hydrate();}}}
async function refreshResults(more=false){const page=state.page;if(!['browse','favorites'].includes(page))return;const epoch=++resultEpoch,old=page==='browse'?state.browseItems:state.favoriteItems||[];try{const result=await catalogPage({category:state.category,version:state.version,source:state.sourceFilter,search:state.search,sort:state.sort,rating:state.minRating,offset:more?old.length:0,ids:page==='favorites'?state.favorites:null});if(epoch!==resultEpoch||page!==state.page)return;const items=more?[...old,...result.items]:result.items;mergeMods(result.items);if(page==='browse'){state.browseItems=items;state.browseHasMore=result.hasMore;}else{state.favoriteItems=items;state.favoritesHasMore=result.hasMore;}const target=$('#results');if(target){target.innerHTML=views.grid(items,page)+(result.hasMore?`<button class="soft-button full" data-action="catalog-more">${t('Load more','عرض المزيد')}</button>`:'');hydrate();}}catch(e){if(epoch===resultEpoch)toast(e.message);}}
async function loadStudio(more=false){if(state.user?.role!=='admin')return;const key=state.studioCategory+state.studioSort;try{const result=await catalogPage({category:state.studioCategory,sort:state.studioSort,offset:more?(state.studioItems?.length||0):0,limit:24});if(key!==state.studioCategory+state.studioSort)return;state.studioItems=more?[...(state.studioItems||[]),...result.items]:result.items;state.studioHasMore=result.hasMore;state.studioLimit=Math.max(24,state.studioItems.length);mergeMods(result.items);if(state.page==='studio')refreshStudio();}catch(e){toast(e.message);}}
async function loadSources(){state.sourcesLoading=true;state.sourcesError='';render();try{state.sources=await api('/sources');}catch(e){state.sourcesError=t('Content Hub backend not configured or unreachable. ','Backend ديال Content Hub غير مهيأ أو غير متاح. ')+e.message;}finally{state.sourcesLoading=false;if(state.page==='sources')render();}}
function openSource(m){const url=externalURL(sourceLink(m)||m.sourceUrl||m.downloadUrl);if(!url)return toast(t('No safe source link supplied.','ما كاينش رابط مصدر آمن.'));modal(`<div class="padded-modal"><p class="eyebrow">${esc(m.source)}</p><h2>${t('Continue to the creator','المتابعة عند المبدع')}</h2><p>${t('This opens the original website. Craftly does not host this file or verify external downloads. Check the creator’s license and instructions.','غادي يتحل الموقع الأصلي. Craftly ما كيستاضفش هاد الملف وما كيضمنش التحميل الخارجي. راجع ترخيص وتعليمات المبدع.')}</p><p dir="ltr">${esc(new URL(url).hostname)}</p><button class="primary full" data-open-external="${esc(url)}">${icon('arrow-up-right')}${t('Open original source','فتح المصدر الأصلي')}</button></div>`,'sheet');}
document.addEventListener('click',async e=>{const el=e.target.closest('button,a[data-page]');if(!el)return;try{
 if(el.dataset.page){e.preventDefault();navigate(el.dataset.page);return;}
 if(el.dataset.category){state.category=el.dataset.category;render();refreshResults();return;}
 if(el.dataset.homeBrowse){const def=HOME_SECTIONS.find(s=>s[0]===el.dataset.homeBrowse);state.category=def[3];state.sort=def[4];state.sourceFilter='all';state.search='';state.scrollPositions.browse=0;navigate('browse');return;}
 if(el.dataset.homeMore)return loadSection(el.dataset.homeMore,true);
 if(el.dataset.sourceLink)return openSource(state.mods.find(m=>m.id===el.dataset.sourceLink));
 if(el.dataset.openExternal){const url=externalURL(el.dataset.openExternal);if(url){if(native?.openExternal)native.openExternal(url);else window.open(url,'_blank','noopener,noreferrer');close();}return;}
 if(el.dataset.sourceToggle||el.dataset.sourceSync){el.disabled=true;await api('/sources/action',{method:'POST',body:JSON.stringify({action:el.dataset.sourceSync?'sync':'toggle',source:el.dataset.sourceSync||el.dataset.sourceToggle,enabled:el.dataset.enabled==='true'})});if(el.dataset.sourceToggle&&el.dataset.enabled==='false'){const source=el.dataset.sourceToggle;for(const key of ['mods','browseItems','favoriteItems','studioItems','heroItems'])if(state[key])state[key]=state[key].filter(m=>m.source!==source);state.homeSections={};state.heroFetchedAt=0;}await loadSources();toast(t('Source request accepted. Refresh to see progress.','تم قبول الطلب. حدّث لعرض التقدم.'));return;}
 if(el.dataset.mod)return detail(el.dataset.mod);
 if(el.dataset.favorite)return favorite(el.dataset.favorite);
 if(el.dataset.download)return download(el.dataset.download);
 if(el.dataset.transfer){state.returnPage='downloads';state.transferId=el.dataset.transfer;state.page='transfer';render();window.scrollTo({top:0});return;}
 if(el.dataset.transferAction){const act=el.dataset.transferAction;await transfers[act]?.(el.dataset.id);if(act==='open'&&!native)toast(t('Saved to browser downloads. Open the file from your device to import it.','تم الحفظ عبر المتصفح. افتح الملف من هاتفك لاستيراده.'));return;}
 if(el.dataset.tab){state.detailTab=el.dataset.tab;const y=scrollY;render();window.scrollTo({top:y});return;}
 if(el.dataset.rate){if(!state.user)return forms.login();await api('/mods/'+el.dataset.rate+'/rating',{method:'POST',body:JSON.stringify({rating:Number(el.dataset.value)})});const refreshed=await catalogPage({ids:[el.dataset.rate],force:true});mergeMods(refreshed.items);render();toast(t('Thanks for your rating.','شكراً على تقييمك.'));return;}
 if(el.dataset.delete){modal(`<div class="padded-modal"><h2>${t('Remove this add-on?','حذف هذه الإضافة؟')}</h2><p>${state.mods.find(m=>m.id===el.dataset.delete)?.sourceType==='external'?t('Hide this imported entry and block reimport. The original creator’s files and website are not changed.','إخفاء العنصر ومنع استيراده مجدداً. ملفات المبدع والموقع الأصلي لا يتغيران.'):t('This removes the catalog entry and requests deletion of its cloud files. Files already downloaded to phones are not removed.','يحذف الإضافة وملفاتها السحابية، ولا يحذف النسخ الموجودة على الهواتف.')}</p><button class="primary full danger-button" data-confirm-delete="${esc(el.dataset.delete)}">${t('Remove add-on','حذف الإضافة')}</button><button class="soft-button full" data-action="close">${t('Keep it','إلغاء')}</button></div>`,'sheet');return;}
 if(el.dataset.confirmDelete){el.disabled=true;const id=el.dataset.confirmDelete;const r=await api('/admin/mods/'+id,{method:'DELETE'});state.mods=state.mods.filter(m=>m.id!==id);state.studioItems=(state.studioItems||[]).filter(m=>m.id!==id);state.heroItems=state.heroItems.filter(m=>m.id!==id);state.homeSections={};state.favorites=state.favorites.filter(f=>f!==id);state.downloads=state.downloads.filter(d=>d.modId!==id);close();render();toast(r.warning||t('Add-on removed.','تم حذف الإضافة.'));return;}
 const a=el.dataset.action;
 if(a==='close')close();if(a==='back')navigate(state.returnPage||'browse');
 if(a==='login')forms.login();if(a==='admin-login')forms.login(false,true);if(a==='register')forms.login(true);
 if(a==='settings')settings();if(a==='storage')storage();if(a==='notifications')notifications();if(a==='filters')modal(views.filtersSheet(),'sheet');if(a==='versions')modal(views.versionsSheet(),'sheet');
 if(a==='help')forms.help();if(a==='upload')forms.upload();if(a==='retry'){close();await load({force:true});}
 if(a==='language'){state.ar=!state.ar;localStorage.setItem('craftly-lang',state.ar?'ar':'en');close();render();}
 if(a==='password'){const p=$('.password-input input');p.type=p.type==='password'?'text':'password';el.setAttribute('aria-label',p.type==='text'?t('Hide password','إخفاء كلمة المرور'):t('Show password','إظهار كلمة المرور'));}
 if(a==='studio')navigate('studio');
 if(a==='studio-layout'){state.studioLayout=state.studioLayout==='grid'?'list':'grid';render();}
 if(a==='studio-more')loadStudio(true);
 if(a==='catalog-more')refreshResults(true);
 if(a==='sources')navigate('sources');
 if(a==='sources-refresh')loadSources();
 if(a==='welcome-skip'){navigate(state.admin?'studio':'discover');load();}
 if(a==='about')modal(`<div class="padded-modal about-modal"><div class="about-logo">${icon('box')}</div><h2>Craftly <span>1.4</span></h2><p>${t('A little upgrade. A whole new world.','إضافة صغيرة. عالم جديد بالكامل.')}</p><div class="info-note">${icon('info')}<p>${t('Independent Minecraft Bedrock companion. Not affiliated with Mojang or Microsoft. Catalog ratings and download counts come from your connected project. Counts are unique requests, not verified installations.','تطبيق مستقل لـMinecraft Bedrock، غير تابع لـMojang أو Microsoft. بيانات الكتالوج من مشروعك. الأرقام طلبات تنزيل فريدة وليست تأكيد تثبيت.')}</p></div></div>`,'sheet');
 if(a==='clear-confirm')modal(`<div class="padded-modal"><h2>${t('Clear Craftly’s local files?','مسح ملفات Craftly المحلية؟')}</h2><p>${t('You can download the add-ons again. Cloud data and files in the phone’s Downloads folder are kept.','يمكن إعادة تنزيل الإضافات. البيانات السحابية ونسخ مجلد تنزيلات الهاتف تبقى محفوظة.')}</p><button class="primary full danger-button" data-action="clear-files">${t('Clear files','مسح الملفات')}</button><button class="soft-button full" data-action="close">${t('Cancel','إلغاء')}</button></div>`,'sheet');
 if(a==='clear-files'){transfers.clear();close();render();toast(t('Local files cleared.','تم مسح الملفات المحلية.'));}
 if(a==='reset-filters'){const f=$('#filters-form');f.elements.sort.value='new';f.elements.category.value='All mods';f.elements.rating.value='0';f.elements.source.value='all';}
 if(a==='logout-confirm')modal(`<div class="padded-modal"><h2>${t('Sign out of Craftly?','تسجيل الخروج؟')}</h2><p>${t('Active downloads will be canceled. Your cloud favorites stay saved.','سيتم إلغاء التنزيلات الجارية. المفضلة السحابية تبقى محفوظة.')}</p><button class="primary full" data-action="logout">${t('Sign out','تسجيل الخروج')}</button><button class="soft-button full" data-action="close">${t('Stay here','البقاء')}</button></div>`,'sheet');
 if(a==='logout'){loadEpoch++;await api('/auth/logout',{method:'POST'});state.user=null;state.downloads=[];transfers.setOwner(null);state.favorites=readJSON('craftly-guest-favorites',[]);close();navigate('account');}
 }catch(err){toast(err.message);el.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.name==='downloadUrl')$('#publish-package').required=!e.target.value.trim();if(e.target.id==='search'){state.search=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>refreshResults(),200);}if(e.target.id==='publish-title')$('#title-count').textContent=e.target.value.length+'/80';if(e.target.id==='publish-description')$('#description-count').textContent=e.target.value.length+'/5000';});
document.addEventListener('change',e=>{if(e.target.id==='studio-category'){state.studioCategory=e.target.value;state.studioLimit=30;refreshStudio();loadStudio();}if(e.target.id==='studio-sort'){state.studioSort=e.target.value;state.studioLimit=30;refreshStudio();loadStudio();}if(e.target.name==='downloadUrl')$('#publish-package').required=!e.target.value.trim();if(e.target.closest('#upload-form')&&e.target.type==='file'&&e.target.name!=='screenshots')fileSelection(e.target);if(e.target.name==='screenshots')$('#screenshots-status').textContent=e.target.files.length+' / 6 '+t('screenshots selected','صور مختارة');});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]');if(!b)return;const original=b.innerHTML;b.disabled=true;b.textContent=t('Just a moment…','لحظة من فضلك…');try{
 if(f.id==='filters-form'){const d=new FormData(f);state.sort=d.get('sort');state.category=d.get('category');state.minRating=Number(d.get('rating'));state.sourceFilter=d.get('source')||'all';close();render();refreshResults();}
 if(f.id==='version-form'){state.version=new FormData(f).get('version');state.homeSections={};state.homeScroll={};state.heroIndex=0;close();const hero=await catalogPage({sort:'updated',version:state.version,limit:5});state.heroItems=hero.items;state.heroFetchedAt=Date.now();mergeMods(hero.items);render();refreshResults();}
 if(f.id==='resend-form'){await api('/auth/resend',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});toast(t('Check your inbox.','شوف البريد ديالك.'));}
 if(f.id==='auth-form'){const d=Object.fromEntries(new FormData(f));const r=await api('/auth/'+(f.dataset.register==='true'?'register':'login'),{method:'POST',body:JSON.stringify(d)});if(r.confirmationRequired){forms.confirmation(d.email);return;}if(f.dataset.admin==='true'&&r.user?.role!=='admin'){await api('/auth/logout',{method:'POST'});throw Error(t('This account is not an administrator.','هذا الحساب ما عندوش صلاحيات الأدمن.'));}localStorage.setItem('craftly-welcome-seen-v1','1');if(r.user.role==='admin'&&(state.admin||f.dataset.admin==='true'))state.page='studio';else if(state.page==='welcome')state.page='discover';close();await load({force:true});toast(t('Welcome back, explorer.','مرحبا برجوعك.'));}
 if(f.id==='upload-form'){const d=new FormData(f);d.set('distributionConfirmed','true');state.uploading=true;f.querySelectorAll('input,select,textarea').forEach(el=>el.disabled=true);try{const added=await api('/admin/mods',{method:'POST',body:d,onProgress:uploadStage});state.mods=[added,...state.mods.filter(m=>m.id!==added.id)];state.studioItems=[added,...(state.studioItems||[]).filter(m=>m.id!==added.id)];state.homeSections={};state.heroItems=[added,...state.heroItems.filter(m=>m.id!==added.id)].slice(0,5);state.studioCategory='All mods';state.studioSort='new';state.page='studio';state.uploading=false;close();render();toast(t('Published. Your next adventure is live.','تم النشر بنجاح.'));}finally{state.uploading=false;f.querySelectorAll('input,select,textarea').forEach(el=>el.disabled=false);}}
 }catch(err){const progress=$('#upload-progress');if(f.id==='upload-form'&&progress){progress.hidden=true;$('#package-file-status').textContent=t('Upload not completed · retry when ready','لم يكتمل الرفع · أعد المحاولة');}const error=f.querySelector('.form-error');if(error)error.textContent=err.message;else toast(err.message);}finally{b.disabled=false;b.innerHTML=original;hydrate();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#search')?.focus();}if(e.key==='Tab'&&$('.modal')){const list=[...$('.modal').querySelectorAll('button:not(:disabled),input:not([type=hidden]),select,textarea,a[href]')];const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
$('#overlay').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))close();});
cloud.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){const wasAuthenticated=!!state.user;loadEpoch++;loadTask=null;state.user=null;state.mods=[];state.homeSections={};state.browseItems=[];state.favoriteItems=null;state.loading=false;state.downloads=[];transfers.setOwner(null);state.favorites=readJSON('craftly-guest-favorites',[]);if(wasAuthenticated)close();render();if(wasAuthenticated&&state.page!=='welcome'&&!state.uploading)queueMicrotask(()=>load({force:true}));}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.page==='discover')mountHome();});
window.addEventListener('beforeunload',e=>{if(state.uploading){e.preventDefault();e.returnValue='';}});
window.addEventListener('online',()=>{if(state.page!=='welcome'&&!state.uploading)load();});
async function boot(){
 const started=performance.now(),hint=readJSON('craftly-supabase-v1',null),seen=localStorage.getItem('craftly-welcome-seen-v1')==='1';
 let session=null;
 const recovery=cloud.auth.getSession().then(({data})=>{session=data.session;}).catch(()=>{});
 state.page=state.admin?'studio':'discover';
 // Returning visitors recover their real session/catalog in parallel with the splash.
 // The local hint only chooses a loading screen; it never grants an identity or role.
 const warming=(hint?.access_token||seen)?load():null;
 await new Promise(resolve=>setTimeout(resolve,Math.max(0,2000-(performance.now()-started))));
 await Promise.race([recovery,new Promise(resolve=>setTimeout(resolve,0))]);
 if(session)localStorage.setItem('craftly-welcome-seen-v1','1');
 const hasSession=!!(session||hint?.access_token);
 if(shouldShowWelcome({hasSession,seen})){localStorage.setItem('craftly-welcome-seen-v1','1');state.page='welcome';state.loading=false;render();}
 else if(warming)render();else load();
 const splash=$('#startup-splash');splash?.classList.add('leaving');native?.setDarkAppearance?.(state.page==='welcome');setTimeout(()=>splash?.remove(),260);
}
boot();
