import {cloudApi,cloud} from './cloud.js';
import {SUPABASE_URL} from './cloud-config.js';
import {createViews} from './views.js';
import {createForms} from './forms.js';
import {createTransfers} from './transfers.js';
import './style.css';
import {createIcons,House,Bell,ArrowLeft,Paintbrush,SlidersHorizontal,Pause,Play,Gauge,Clock3,CalendarDays,CircleHelp,Cloud,RefreshCw,ArrowRight,ArrowUpRight,ArrowDownWideNarrow,Box,Boxes,Blocks,ChevronRight,ChevronDown,Gamepad2,Compass,Heart,Download,Sparkles,LayoutDashboard,Settings2,UserRound,Cuboid,Grid2x2,Puzzle,Layers2,Earth,Shirt,Search,CloudOff,Flame,Star,PackageCheck,PackageOpen,Plus,Image,Eye,Trash2,X,ShieldCheck,LockKeyhole,HardDrive,Info,Check,Languages,ImagePlus,PackagePlus,Send,LogOut} from 'lucide';
const icons={House,Bell,ArrowLeft,Paintbrush,SlidersHorizontal,Pause,Play,Gauge,Clock3,CalendarDays,CircleHelp,Cloud,RefreshCw,ArrowRight,ArrowUpRight,ArrowDownWideNarrow,Box,Boxes,Blocks,ChevronRight,ChevronDown,Gamepad2,Compass,Heart,Download,Sparkles,LayoutDashboard,Settings2,UserRound,Cuboid,Grid2x2,Puzzle,Layers2,Earth,Shirt,Search,CloudOff,Flame,Star,PackageCheck,PackageOpen,Plus,Image,Eye,Trash2,X,ShieldCheck,LockKeyhole,HardDrive,Info,Check,Languages,ImagePlus,PackagePlus,Send,LogOut};
const native=window.CraftlyNative;
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const state={page:'discover',returnPage:'discover',category:'All mods',version:'all',minRating:0,search:'',sort:'new',mods:[],user:null,favorites:readJSON('craftly-guest-favorites',[]),downloads:[],loading:true,error:'',admin:new URLSearchParams(location.search).has('admin')||native?.isAdmin(),ar:localStorage.getItem('craftly-lang')==='ar',detailTab:'about',detailId:null,transferId:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(en,ar)=>state.ar?ar:en;
const icon=(name)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const image=m=>m.image||'images/overworld.webp';
const count=n=>Intl.NumberFormat('en',{notation:'compact'}).format(n||0);
const mb=n=>(Number(n||0)/1048576).toFixed(1)+' MB';
function hydrate(){createIcons({icons,attrs:{'stroke-width':1.75}});document.querySelectorAll('img').forEach(img=>{img.onerror=()=>{if(!img.dataset.fallback){img.dataset.fallback='1';img.src='images/overworld.webp';img.alt=t('Image unavailable · Craftly artwork','الصورة غير متاحة · صورة Craftly');}};});}
async function api(url,opts={}){try{return await cloudApi(url,opts);}catch(e){if(/fetch|network/i.test(e.message))throw Error(t('Cannot reach Supabase. Check your connection and retry.','تعذر الاتصال بـSupabase. تأكد من الإنترنت وحاول من جديد.'));throw e;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
let progressTimer;
const transfers=createTransfers({native,ticket:id=>api('/mods/'+id+'/download',{method:'POST'}),onChange:()=>{clearTimeout(progressTimer);progressTimer=setTimeout(()=>{if(state.page==='downloads'&&$('#results')){$('#results').innerHTML=views.downloadResults();hydrate();}if(state.page==='transfer'&&$('#main')){$('#main').innerHTML=views.transferDetail();hydrate();}},80);}});
const views=createViews({state,t,icon,esc,image,count,mb,transfers});
const forms=createForms({state,t,icon,esc,image,count,mb,heading:views.heading,modal,catLabel:views.catLabel,categories:views.categories});
function pageContent(){if(state.page==='studio')return forms.studio();if(state.page==='detail')return views.detail();if(state.page==='transfer')return views.transferDetail();return views[state.page]?.()||views.discover();}
function render(){document.documentElement.lang=state.ar?'ar':'en';document.documentElement.dir=state.ar?'rtl':'ltr';document.body.dataset.page=state.page;$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#" data-page="discover"><span>${icon('box')}</span>craftly<span class="brand-dot">.</span></a><div class="sidebar-label">${t('YOUR LITTLE WORLD','عالمك الصغير')}</div><nav>${views.nav()}</nav><div class="sidebar-bottom"><div class="sidebar-art"><img src="images/cottage.webp" alt="Minecraft cottage"><div><b>${t('A little more wonder.','قليل من السحر.')}</b><p>${t('Make Minecraft yours.','ماينكرافت، على ذوقك.')}</p></div></div><button class="menu-row" data-action="studio">${icon('layout-dashboard')}<b>${t('Creator studio','استوديو الأدمن')}</b>${icon('arrow-up-right')}</button><small>Craftly 1.2 · Bedrock Edition</small></div></aside><div class="main-shell">${views.topbar()}<main id="main">${pageContent()}</main><footer class="footer">${t('An independent Minecraft companion. Not affiliated with Mojang or Microsoft.','تطبيق مستقل وغير تابع لـMojang أو Microsoft.')}<span>© ${new Date().getFullYear()} Craftly</span></footer></div><nav class="mobile-nav" aria-label="${t('Main navigation','التنقل الرئيسي')}">${views.nav()}</nav>`;hydrate();}
function modal(content,cls=''){window.lastFocus=document.activeElement;$('#overlay').innerHTML=`<div class="modal-backdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="Craftly"><button class="modal-close icon-button" data-action="close" aria-label="${t('Close','إغلاق')}">${icon('x')}</button>${content}</section></div>`;document.body.classList.add('modal-open');hydrate();setTimeout(()=>$('.modal input:not([type=hidden]), .modal button')?.focus(),40);}
function close(){$('#overlay').innerHTML='';document.body.classList.remove('modal-open');window.lastFocus?.isConnected&&window.lastFocus.focus();}
function navigate(page){close();state.page=page;state.search='';if(['browse','discover','favorites'].includes(page))state.category='All mods';render();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});if(page==='downloads'&&state.user)api('/downloads').then(d=>{state.downloads=d;if(state.page==='downloads')render();}).catch(e=>toast(e.message));}
function detail(id){if(!state.mods.some(m=>m.id===id))return toast(t('This add-on is no longer available.','هذه الإضافة لم تعد متوفرة.'));if(state.page!=='detail')state.returnPage=state.page;state.detailId=id;state.detailTab='about';state.page='detail';close();render();window.scrollTo({top:0});}
async function load(){state.loading=true;state.error='';render();try{const u=await api('/me');state.user=u;transfers.setOwner(u?.id);state.mods=await api('/mods');if(u){state.favorites=u.favorites;state.downloads=await api('/downloads');}else{state.favorites=readJSON('craftly-guest-favorites',[]);state.downloads=[];}}catch(e){state.error=e.message;}finally{state.loading=false;render();}}
async function favorite(id){try{state.favorites=state.user?await api('/favorites/'+id,{method:'POST'}):state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];if(!state.user)localStorage.setItem('craftly-guest-favorites',JSON.stringify(state.favorites));const y=scrollY;render();window.scrollTo({top:y});toast(state.favorites.includes(id)?t('Saved to your favorites.','تمت الإضافة للمفضلة.'):t('Removed from favorites.','تمت الإزالة من المفضلة.'));}catch(e){toast(e.message);}}
async function download(id){if(!state.user)return forms.login();const m=state.mods.find(m=>m.id===id);if(!m)return toast(t('Refresh the catalog to download this add-on.','حدث الكتالوج لتحميل هذه الإضافة.'));close();state.returnPage='downloads';state.page='transfer';state.transferId=id;transfers.start(m);render();window.scrollTo({top:0});}
window.craftlyTransferEvent=event=>{transfers.receive(event);if(event.status==='complete'){toast(t('Download complete. Ready for Minecraft.','اكتمل التنزيل. واجد لماينكرافت.'));api('/downloads').then(d=>state.downloads=d).catch(()=>{});}};
window.craftlyDownloadDone=(ok,message)=>toast(message);
window.craftlyBack=()=>{if($('.modal')){close();return true;}if(['detail','transfer'].includes(state.page)){navigate(state.page==='transfer'?'downloads':state.returnPage);return true;}if(state.page!=='discover'){navigate('discover');return true;}return false;};
function settings(){modal(`<div class="sheet-handle"></div><div class="padded-modal"><p class="eyebrow">YOUR SPACE, YOUR WAY</p><h2>${t('Settings','الإعدادات')}</h2><div class="menu-card"><button class="menu-row" data-action="language">${icon('languages')}<b>${state.ar?'English':'العربية'}</b>${icon('chevron-right')}</button><button class="menu-row" data-action="versions">${icon('box')}<b>${t('Minecraft version','إصدار Minecraft')}</b>${icon('chevron-right')}</button><button class="menu-row" data-action="retry">${icon('refresh-cw')}<b>${t('Refresh catalog','تحديث الكتالوج')}</b>${icon('chevron-right')}</button></div><div class="info-note">${icon('shield-check')}<p>${t('Connected directly to your Supabase project. Your password is never embedded in the app.','ربط مباشر مع مشروع Supabase. كلمة المرور غير مدمجة في التطبيق.')}<br><span dir="ltr">${esc(new URL(SUPABASE_URL).host)}</span></p></div></div>`,'sheet');}
function storage(){let nativeSize=0;try{nativeSize=Number(native?.downloadStorageBytes?.()||0);}catch{}const total=native?nativeSize:[...transfers.jobs.values()].reduce((a,j)=>a+(j.blob?j.bytes:0),0);modal(`<div class="sheet-handle"></div><div class="padded-modal"><p class="eyebrow">ON THIS DEVICE</p><h2>${t('Manage storage','إدارة التخزين')}</h2><div class="storage-summary">${icon('hard-drive')}<strong>${mb(total)}</strong><span>${t('Craftly local files','ملفات Craftly المحلية')}</span></div><p>${t('Clear files retained inside Craftly. This does not delete your account, cloud mods, Minecraft worlds or copies already saved in your phone’s Downloads folder.','مسح الملفات داخل Craftly فقط. لا يحذف الحساب أو المودات السحابية أو عوالم اللعبة أو النسخ المحفوظة في مجلد تنزيلات الهاتف.')}</p><button class="primary full" data-action="clear-confirm">${icon('trash-2')}${t('Clear local files','مسح الملفات المحلية')}</button><p class="field-note">${t('In the browser, only this session’s in-memory files can be cleared.','في المتصفح، يمكن مسح الملفات المحفوظة في ذاكرة هذه الجلسة فقط.')}</p></div>`,'sheet');}
function notifications(){localStorage.setItem('craftly-seen',String(Date.now()));render();const latest=[...state.mods].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,10);modal(`<div class="sheet-handle"></div><div class="padded-modal"><h2>${t('Fresh from your creators','جديد صُنّاع المحتوى')}</h2><p class="muted">${t('Latest published add-ons. These are catalog updates, not push notifications.','آخر الإضافات المنشورة، وليست إشعارات فورية من النظام.')}</p>${latest.length?latest.map(m=>`<button class="notification-row" data-mod="${esc(m.id)}"><img src="${esc(image(m))}" alt=""><span><b>${esc(m.title)}</b><small>${new Date(m.createdAt).toLocaleDateString()}</small></span>${icon('chevron-right')}</button>`).join(''):views.empty('bell',t('All caught up','كلشي محدث'),t('New releases will appear here.','الإضافات الجديدة غادي تظهر هنا.'),false)}</div>`,'sheet');}
function refreshResults(){const target=$('#results');if(!target)return;if(state.page==='browse')target.innerHTML=views.grid(views.filtered());if(state.page==='favorites')target.innerHTML=views.grid(views.filtered(state.mods.filter(m=>state.favorites.includes(m.id))),'favorites');if(state.page==='downloads')target.innerHTML=views.downloadResults();hydrate();}
document.addEventListener('click',async e=>{const el=e.target.closest('button,a[data-page]');if(!el)return;try{
 if(el.dataset.page){e.preventDefault();navigate(el.dataset.page);return;}
 if(el.dataset.category){state.category=el.dataset.category;render();return;}
 if(el.dataset.mod)return detail(el.dataset.mod);
 if(el.dataset.favorite)return favorite(el.dataset.favorite);
 if(el.dataset.download)return download(el.dataset.download);
 if(el.dataset.transfer){state.returnPage='downloads';state.transferId=el.dataset.transfer;state.page='transfer';render();window.scrollTo({top:0});return;}
 if(el.dataset.transferAction){const act=el.dataset.transferAction;await transfers[act]?.(el.dataset.id);if(act==='open'&&!native)toast(t('Saved to browser downloads. Open the file from your device to import it.','تم الحفظ عبر المتصفح. افتح الملف من هاتفك لاستيراده.'));return;}
 if(el.dataset.tab){state.detailTab=el.dataset.tab;const y=scrollY;render();window.scrollTo({top:y});return;}
 if(el.dataset.rate){if(!state.user)return forms.login();await api('/mods/'+el.dataset.rate+'/rating',{method:'POST',body:JSON.stringify({rating:Number(el.dataset.value)})});state.mods=await api('/mods');render();toast(t('Thanks for your rating.','شكراً على تقييمك.'));return;}
 if(el.dataset.delete){modal(`<div class="padded-modal"><h2>${t('Remove this add-on?','حذف هذه الإضافة؟')}</h2><p>${t('This removes the catalog entry and requests deletion of its cloud files. Files already downloaded to phones are not removed.','يحذف الإضافة وملفاتها السحابية، ولا يحذف النسخ الموجودة على الهواتف.')}</p><button class="primary full danger-button" data-confirm-delete="${esc(el.dataset.delete)}">${t('Remove add-on','حذف الإضافة')}</button><button class="soft-button full" data-action="close">${t('Keep it','إلغاء')}</button></div>`,'sheet');return;}
 if(el.dataset.confirmDelete){el.disabled=true;const r=await api('/admin/mods/'+el.dataset.confirmDelete,{method:'DELETE'});close();await load();toast(r.warning||t('Add-on removed.','تم حذف الإضافة.'));return;}
 const a=el.dataset.action;
 if(a==='close')close();if(a==='back')navigate(state.returnPage||'browse');
 if(a==='login')forms.login();if(a==='admin-login')forms.login(false,true);if(a==='register')forms.login(true);
 if(a==='settings')settings();if(a==='storage')storage();if(a==='notifications')notifications();if(a==='filters')modal(views.filtersSheet(),'sheet');if(a==='versions')modal(views.versionsSheet(),'sheet');
 if(a==='help')forms.help();if(a==='upload')forms.upload();if(a==='retry'){close();await load();}
 if(a==='language'){state.ar=!state.ar;localStorage.setItem('craftly-lang',state.ar?'ar':'en');close();render();}
 if(a==='password'){const p=$('.password-input input');p.type=p.type==='password'?'text':'password';el.setAttribute('aria-label',p.type==='text'?t('Hide password','إخفاء كلمة المرور'):t('Show password','إظهار كلمة المرور'));}
 if(a==='studio')navigate('studio');
 if(a==='about')modal(`<div class="padded-modal about-modal"><div class="about-logo">${icon('box')}</div><h2>Craftly <span>1.2</span></h2><p>${t('A little upgrade. A whole new world.','إضافة صغيرة. عالم جديد بالكامل.')}</p><div class="info-note">${icon('info')}<p>${t('Independent Minecraft Bedrock companion. Not affiliated with Mojang or Microsoft. Catalog ratings and download counts come from your connected project. Counts are unique requests, not verified installations.','تطبيق مستقل لـMinecraft Bedrock، غير تابع لـMojang أو Microsoft. بيانات الكتالوج من مشروعك. الأرقام طلبات تنزيل فريدة وليست تأكيد تثبيت.')}</p></div></div>`,'sheet');
 if(a==='clear-confirm')modal(`<div class="padded-modal"><h2>${t('Clear Craftly’s local files?','مسح ملفات Craftly المحلية؟')}</h2><p>${t('You can download the add-ons again. Cloud data and files in the phone’s Downloads folder are kept.','يمكن إعادة تنزيل الإضافات. البيانات السحابية ونسخ مجلد تنزيلات الهاتف تبقى محفوظة.')}</p><button class="primary full danger-button" data-action="clear-files">${t('Clear files','مسح الملفات')}</button><button class="soft-button full" data-action="close">${t('Cancel','إلغاء')}</button></div>`,'sheet');
 if(a==='clear-files'){transfers.clear();close();render();toast(t('Local files cleared.','تم مسح الملفات المحلية.'));}
 if(a==='reset-filters'){const f=$('#filters-form');f.elements.sort.value='new';f.elements.category.value='All mods';f.elements.rating.value='0';}
 if(a==='logout-confirm')modal(`<div class="padded-modal"><h2>${t('Sign out of Craftly?','تسجيل الخروج؟')}</h2><p>${t('Active downloads will be canceled. Your cloud favorites stay saved.','سيتم إلغاء التنزيلات الجارية. المفضلة السحابية تبقى محفوظة.')}</p><button class="primary full" data-action="logout">${t('Sign out','تسجيل الخروج')}</button><button class="soft-button full" data-action="close">${t('Stay here','البقاء')}</button></div>`,'sheet');
 if(a==='logout'){await api('/auth/logout',{method:'POST'});state.user=null;state.downloads=[];transfers.setOwner(null);state.favorites=readJSON('craftly-guest-favorites',[]);close();navigate('account');}
 }catch(err){toast(err.message);el.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;refreshResults();}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]');if(!b)return;const original=b.innerHTML;b.disabled=true;b.textContent=t('Just a moment…','لحظة من فضلك…');try{
 if(f.id==='filters-form'){const d=new FormData(f);state.sort=d.get('sort');state.category=d.get('category');state.minRating=Number(d.get('rating'));close();render();}
 if(f.id==='version-form'){state.version=new FormData(f).get('version');close();render();}
 if(f.id==='resend-form'){await api('/auth/resend',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});toast(t('Check your inbox.','شوف البريد ديالك.'));}
 if(f.id==='auth-form'){const d=Object.fromEntries(new FormData(f));const r=await api('/auth/'+(f.dataset.register==='true'?'register':'login'),{method:'POST',body:JSON.stringify(d)});if(r.confirmationRequired){forms.confirmation(d.email);return;}if(f.dataset.admin==='true'&&r.user?.role!=='admin'){await api('/auth/logout',{method:'POST'});throw Error(t('This account is not an administrator.','هذا الحساب ما عندوش صلاحيات الأدمن.'));}if(r.user.role==='admin'&&(state.admin||f.dataset.admin==='true'))state.page='studio';close();await load();toast(t('Welcome back, explorer.','مرحبا برجوعك.'));}
 if(f.id==='upload-form'){const d=new FormData(f);await api('/admin/mods',{method:'POST',body:d});close();await load();toast(t('Published. Your next adventure is live.','تم النشر بنجاح.'));}
 }catch(err){const error=f.querySelector('.form-error');if(error)error.textContent=err.message;else toast(err.message);}finally{b.disabled=false;b.innerHTML=original;hydrate();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#search')?.focus();}if(e.key==='Tab'&&$('.modal')){const list=[...$('.modal').querySelectorAll('button:not(:disabled),input:not([type=hidden]),select,textarea,a[href]')];const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
$('#overlay').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))close();});
cloud.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){state.user=null;state.downloads=[];transfers.setOwner(null);state.favorites=readJSON('craftly-guest-favorites',[]);close();render();}});
window.addEventListener('online',()=>load());
if(state.admin)state.page='studio';load();
